// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBey4mpmqVOVLYBgGdd1b_BgN3p9N-FhvM',
    appId: '1:860737113481:web:dad9133b60b63d114f2558',
    messagingSenderId: '860737113481',
    projectId: 'chat-app-cac6c',
    authDomain: 'chat-app-cac6c.firebaseapp.com',
    storageBucket: 'chat-app-cac6c.firebasestorage.app',
    measurementId: 'G-2KD81D1SGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxhLAH1J21_LMbbWg3wSSRs22OIonkBlg',
    appId: '1:860737113481:android:1ebb8299e016f4294f2558',
    messagingSenderId: '860737113481',
    projectId: 'chat-app-cac6c',
    storageBucket: 'chat-app-cac6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC09Pch2O_WCsMbHwXUm3h74YrkeOGJvgM',
    appId: '1:860737113481:ios:313594f4e9ad363e4f2558',
    messagingSenderId: '860737113481',
    projectId: 'chat-app-cac6c',
    storageBucket: 'chat-app-cac6c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC09Pch2O_WCsMbHwXUm3h74YrkeOGJvgM',
    appId: '1:860737113481:ios:313594f4e9ad363e4f2558',
    messagingSenderId: '860737113481',
    projectId: 'chat-app-cac6c',
    storageBucket: 'chat-app-cac6c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBey4mpmqVOVLYBgGdd1b_BgN3p9N-FhvM',
    appId: '1:860737113481:web:59392f202b02900e4f2558',
    messagingSenderId: '860737113481',
    projectId: 'chat-app-cac6c',
    authDomain: 'chat-app-cac6c.firebaseapp.com',
    storageBucket: 'chat-app-cac6c.firebasestorage.app',
    measurementId: 'G-LK3X16SPVR',
  );
}
